# Generated by Django 4.1.1 on 2022-10-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="identifier",
            field=models.CharField(default=12, max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="person",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="person",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="password",
            field=models.CharField(default=2, max_length=128, verbose_name="password"),
            preserve_default=False,
        ),
    ]
